### PR TITLE
Added HMAC512, removed deprecated methods, updated to nim 1.6.4

### PR DESCRIPTION
**Pull request by NeonFXFusion**
* Changed csize to csize_t
* Changed cuchar (deprecated) to char
* Changed AssertionError (deprecated) to AssertionDefect
* Commented out questionable memory (un)safe assertion (don't know how to fix)
* Added HMAC512 methods
* Added HMAC512 test cases
* Updated to nim 1.6.4

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
Thanks for the PR. Some commits introduce many unrelated changes and I might have to cherry-pick and reorganize the changes myself unless you want to do it.

**Comment by NeonFXFusion** [comment]
I can do it, just give me an example of how you want it.

**Comment by FedericoCeratto** [comment]
@NeonFXFusion if you can address the comments in the review and also rebase the PR and remove the merge commit would be good.

**Comment by NeonFXFusion** [comment]
Reorganised and opened new PR #31

**Pull request closed without merging**
