### PR TITLE
sodium: add password hashing functions

### PR DESCRIPTION
**Pull request by alaviss**
Closes #13

Probably more tests should be done, but I'm out of idea.

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
Thanks for the contribution! Do you mind adding docstrigs, perhaps runnableExamples, and test hashing and verification for every algo? Thanks

**Comment by alaviss** [comment]
Np, I'll work on them.

Also, the high-level verification/hash to string API only supports the default algo afaict.

For the `byte`-based one it'd make more sense to have a C version pre-compute some hash then have them checked in the testsuite, but I'm lazy at that :p. Still, I can try.

**Comment by jedisct1** [comment]
The verification API can verify anything produced by the current and previous versions of the hash function.

**Comment by alaviss** [comment]
If wanted, I can change the hashed password type to `HashedPassword = distinct string` and provides a convinient `=~` operator for verification.

**Comment by FedericoCeratto** [comment]
Thanks @alaviss . Regarding `=~` I think it's safer to keep the name of procs very explicit and close to upstream libsodium.

**Pull request merged**
